version: "3.7"
services:
  chinachu:
    container_name: chinachu
    image: chinachu-ffmpeg-vaapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
      MIRAKURUN_PATH: "${MIRAKURUN_PATH}"
    ports:
      - "5353:5353"
      - "10772:10772"
      - "20772:20772"
    volumes:
      - ${RULES_PATH}:/usr/local/chinachu/rules.json
      - ${DATA_PATH}:/usr/local/chinachu/data
      - ${VIDEO_PATH}:/usr/local/chinachu/video
    tmpfs:
      - /tmp
    devices:
      - /dev/dri:/dev/dri
    restart: always
