# https://github.com/Chinachu/Mirakurun/blob/master/doc/Configuration.md

- name: MX
  type: GR
  channel: "20"

- name: CX
  type: GR
  channel: "21"

- name: TBS
  type: GR
  channel: "22"

- name: TX
  type: GR
  channel: "23"

- name: EX
  type: GR
  channel: "24"

- name: NTV
  type: GR
  channel: "25"

- name: NHK E
  type: GR
  channel: "26"

- name: NHK G
  type: GR
  channel: "27"
