version: "3.7"
services:
  mirakurun:
    container_name: mirakurun
    image: chinachu/mirakurun:3.8.0
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    environment:
      TZ: Asia/Tokyo
      # LOG_LEVEL: "3"
      # DEBUG: "true"
    ports:
      - 40772:40772
      - 9229:9229
    devices:
      - /dev/bus:/dev/bus
      - /dev/dvb:/dev/dvb
    volumes:
      - type: bind
        source: /opt/mirakurun/run/
        target: /var/run/
      - type: bind
        source: /opt/mirakurun/opt/
        target: /opt/
      - type: bind
        source: /opt/mirakurun/config/
        target: /app-config/
      - type: bind
        source: /opt/mirakurun/data/
        target: /app-data/
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 10m
